services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dreamnet

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant-storage:/qdrant/storage
    networks:
      - dreamnet

  embedding-server:
    build: ./embedding-server
    container_name: embedding-server
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    networks:
      - dreamnet

volumes:
  qdrant-storage:

networks:
  dreamnet:
    name: dreamnet